version: "3.3"

volumes:
  node_modules:
  data:

services:
  web:
    image: nginx
    volumes:
      - './development/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "80:80"
    restart:
      unless-stopped
    networks:
      - diamond

  frontend:
    build:
      context: ./development/docker
    ports:
      - "3000:3000"
    volumes:
      - '.:/opt/app/'
      - './node_modules:/opt/app/node_modules'
    restart: unless-stopped
    networks:
      - diamond

  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - data:/data
    networks:
      - diamond

networks:
  diamond:
    driver: bridge
